FROM python:3.9.18-slim-bookworm

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

# Set NLTK data path
RUN python -c "import nltk; nltk.download(['punkt', 'stopwords','wordnet'], download_dir='/usr/local/share/nltk_data')"

COPY . /app/

EXPOSE 5000

CMD ["python", "app.py"]
